# Generated by Django 4.1 on 2022-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_maincat_myproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30)),
                ('ppic', models.ImageField(null=True, upload_to='static/profile/')),
                ('passwd', models.CharField(max_length=60)),
                ('address', models.TextField()),
            ],
        ),
    ]
