# Generated by Django 4.1 on 2022-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mcart_morder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='ppic',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='mcart',
            name='cdate',
            field=models.CharField(max_length=100),
        ),
    ]
